/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcountFrom: typeof import('./src/components/AcountFrom.vue')['default']
    Avatar: typeof import('./src/components/global/Avatar.vue')['default']
    Btn: typeof import('./src/components/global/Btn.vue')['default']
    CardItem: typeof import('./src/components/card/CardItem.vue')['default']
    Cntr: typeof import('./src/components/global/Cntr.vue')['default']
    Coin: typeof import('./src/components/global/Coin.vue')['default']
    Dropdown: typeof import('./src/components/Dropdown.vue')['default']
    EmojiAvatar: typeof import('./src/components/global/EmojiAvatar.vue')['default']
    FilterItem: typeof import('./src/components/filter/FilterItem.vue')['default']
    Form: typeof import('./src/components/Form.vue')['default']
    Header: typeof import('./src/components/ui/Header.vue')['default']
    Iagree: typeof import('./src/components/ui/Iagree.vue')['default']
    ItemPrice: typeof import('./src/components/ui/ItemPrice.vue')['default']
    Line: typeof import('./src/components/global/Line.vue')['default']
    ListActivity: typeof import('./src/components/list/ListActivity.vue')['default']
    ListItem: typeof import('./src/components/list/ListItem.vue')['default']
    ListTag: typeof import('./src/components/list/ListTag.vue')['default']
    ListTransaction: typeof import('./src/components/list/ListTransaction.vue')['default']
    ListUser: typeof import('./src/components/list/ListUser.vue')['default']
    Logo: typeof import('./src/components/ui/Logo.vue')['default']
    Media: typeof import('./src/components/global/Media.vue')['default']
    Name: typeof import('./src/components/global/Name.vue')['default']
    NavExplore: typeof import('./src/components/NavExplore.vue')['default']
    Notification: typeof import('./src/components/ui/Notification.vue')['default']
    Price: typeof import('./src/components/global/Price.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select.vue')['default']
    Selector: typeof import('./src/components/Selector.vue')['default']
    Stat: typeof import('./src/components/ui/Stat.vue')['default']
    TimeLeft: typeof import('./src/components/ui/TimeLeft.vue')['default']
    UserLink: typeof import('./src/components/ui/UserLink.vue')['default']
  }
}
