/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AcountFrom: typeof import('./src/components/AcountFrom.vue')['default']
    Btn: typeof import('./src/components/global/Btn.vue')['default']
    Cntr: typeof import('./src/components/global/Cntr.vue')['default']
    Dropdown: typeof import('./src/components/global/Dropdown.vue')['default']
    Line: typeof import('./src/components/global/Line.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
